### ISSUE TITLE
Modal para pedir confirmación de borrado

### ISSUE THREAD

**Issue by LAS1819** [LAS1819/Proyecto_Final_DAW_LAS1920#1]
He intentado asociar un modal de Bootstrap al botón de borrado, para que pida confirmación antes de borrar, pero no consigo validar el borrado.

El modal me salta correctamente pero pierdo el _id_ de la Incidencia y no sé cómo capturarlo... supongo que JavaScript será mi salvador en estos casos.

De momento desconecto la funcionalidad del modal para mejorar la experiencia de la aplicación de cara a grabar la demo para la defensa del proyecto.

**Comment by pedroprieto** [comment]
Buenas Lluís,

La solución pasa por abrir el modal vía Javascript: https://getbootstrap.com/docs/4.0/components/modal/#via-javascript en lugar de hacerlo a través de atributos: https://getbootstrap.com/docs/4.0/components/modal/#via-data-attributes

La idea es crear el botón de Borrar y asociarle un manejador de eventos que llame a una función `borrar`, que lleve como parámetro el `id` de la incidencia. Dicha función activará el modal [a través de JS](https://getbootstrap.com/docs/4.0/components/modal/#via-javascript).

El modal tendrá a su vez dos botones: el de cancelar, que simplemente cerrará el modal (vía JS o vía atributos, este da igual) y el de aceptar. El botón de aceptar deberá realizar la petición de borrado y cerrar el modal vía JS.
